//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Multiwcf.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Department
    {
        public int DeptID { get; set; }
        public int EmployeeID { get; set; }
        public string Course { get; set; }
        public string City { get; set; }
        public string DeptName { get; set; }
        public Nullable<int> Marks { get; set; }
    }
}
